version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development